import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LenisScrollProvider from "./provider/lenis-provider";
import LoadProvider from "./provider/load-provider";
// import ReactLenis from "@studio-freight/react-lenis";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "The Real Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-black text-white antialiased`}
      >
        {/* <ReactLenis root>{children}</ReactLenis> */}

        <LoadProvider>
          <LenisScrollProvider>{children}</LenisScrollProvider>
        </LoadProvider>
      </body>
    </html>
  );
}
